import { readFile, writeFile } from 'node:fs/promises';
const catalogue = JSON.parse(await readFile(new URL('../catalog/tools.json', import.meta.url), 'utf8'));
const check = process.argv.includes('--check');
const appOnly = catalogue.tools.filter(tool => !tool.visibility.includes('model'));
const lines = [
  '# Tool reference', '',
  'Generated from [catalog/tools.json](../catalog/tools.json). Update the snapshot and run npm run docs; do not edit this file by hand.',
  '',
  'Server version: **' + catalogue.serverVersion + '**. Snapshot: **' + catalogue.capturedOn + '**.',
  'Descriptors: **' + catalogue.tools.length + '**; model-callable: **' + (catalogue.tools.length - appOnly.length) + '**; app-only: **' + appOnly.length + '**.',
  '',
  'Live discovery and get_workspace_capabilities determine current schemas and access. Authentication is OAuth and the transport is Streamable HTTP.',
  'Input/output JSON Schemas are included for every tool in the machine-readable catalogue. Required scopes do not replace brand access or approval/spending policy.',
  '',
  '## Scope catalogue', '',
  '| Scope | Purpose |', '| --- | --- |',
  ...Object.entries(catalogue.scopes).map(([scope, text]) => '| ' + scope + ' | ' + text.replaceAll('|', '\\|') + ' |'),
  '', '## Tools', '',
];
for (const tool of catalogue.tools) {
  lines.push('### ' + tool.name, '',
    '**Scope:** ' + tool.scope + '. **Visibility:** ' + (tool.visibility.includes('model') ? 'model and app' : 'app only') + '.',
    '', tool.description, '',
    '**Required input:** ' + (tool.inputSchema.required?.join(', ') || 'none') + '.',
    '',
    '| Parameter | Type | Required |', '| --- | --- | --- |');
  for (const [name, field] of Object.entries(tool.inputSchema.properties ?? {})) {
    const type = field.type ?? (field.anyOf ? 'union' : field.$ref ? 'reference' : 'object');
    lines.push('| ' + name + ' | ' + (Array.isArray(type) ? type.join(' / ') : type) + ' | ' +
      (tool.inputSchema.required?.includes(name) ? 'yes' : 'no') + ' |');
  }
  lines.push('', 'Full constraints, nested settings and output schema: [machine-readable catalogue](../catalog/tools.json).', '');
}
const generated = lines.join('\n').trimEnd() + '\n';
const target = new URL('../docs/tools.md', import.meta.url);
if (check) {
  if (await readFile(target, 'utf8') !== generated) throw new Error('Generated tool docs are stale. Run npm run docs.');
  console.log('Generated tool reference is current.');
} else {
  await writeFile(target, generated);
  console.log('Generated ' + catalogue.tools.length + ' tool entries.');
}
